volumes:
  node_modules:

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend/nuxt:/app/nuxt
      - node_modules:/app/nuxt/node_modules
    ports:
      - "${NUXT_PORT}:3000"
    environment:
      - TZ=${TZ}
